version: "3.8"
services:
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports: 
      - 3000:3000
    volumes:
      - ./frontend/:/usr/src
  backend:
    depends_on:
      - db
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports: 
      - 5000
    volumes:
      - ./backend/:/src/app
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: postgres
  db:
    image: postgres:12 
    restart: always
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/data/postgres
    ports:
      - "5432:5432"

volumes:
  pgdata:
    driver: local
